<CheckCode>:
    name: 'Check'
    md_bg_color: root.color_background()

    FloatLayout:
        MDTopAppBar:
            type: "small"
            pos_hint: {"center_x": .5, "top": 1}
            theme_bg_color: "Custom"
            md_bg_color: root.color_background()


            MDTopAppBarLeadingButtonContainer:

                MDActionTopAppBarButton:
                    icon: 'arrow-left'
                    on_release: root.call_send_code()

            MDTopAppBarTitle:
                text: "Aplicativo de verificação"
                halign: 'center'

        AsyncImage:
            id: icon
            source: root.icon_tema()
            size_hint: None, None
            size: "200dp", "150dp"
            pos_hint: {"center_x": 0.5, "center_y": 0.75}
            allow_stretch: True

        MDLabel:
            text: 'Insira seu codigo de verificação'
            bold: True
            size_hint: None, None
            size: "200dp", "100dp"
            font_style: "Title"
            role: "large"
            pos_hint: {"center_x": 0.5, "center_y": 0.55}
            halign: "center"

        MDLabel:
            text: 'Insira o codigo de verificação, enviado pelo email, na proxima tela para concluir a verificação'
            size_hint: None, None
            size: "320dp", "150dp"
            font_style: "Body"
            role: "medium"
            pos_hint: {"center_x": 0.5, "center_y": 0.45}
            halign: "center"


        MDButton:
            style: "tonal"
            pos_hint: {'top': .2, "center_x": 0.5}
            theme_width: "Custom"
            theme_bg_color: "Custom"
            height: "52dp"
            size_hint_x: .8
            md_bg_color: 0, 0, 0.9, 1
            on_release: root.call_write_code()

            MDButtonText:
                text: "Avançar"
                theme_text_color: "Custom"
                text_color: "white" if root.theme_cls.theme_style == "Dark" else "black"
                font_style: "Title"
                bold: True
                pos_hint: {"center_y": 0.50, "center_x": 0.5}
                role: "medium"
