#: import NavigationsButtons libs.components.navigation_buttons.NavigationsButtons

<RegisterScreen>:
    name: 'Register'
    md_bg_color: 1, 1, 1, 1

    FloatLayout:
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'center_y': 0.95, 'right': 0.15}
            theme_font_size: 'Custom'
            font_size: '30dp'
            halign: 'center'

            theme_icon_color: 'Custom'
            icon_color: 'black'
            on_release: root.init()

        MDLabel:
            text: 'Cadastrar conta'
            font_style: 'Display'
            role: 'small'
            halign: 'center'
            pos_hint: {'center_y': 0.85 , 'center_x': 0.5}

        AsyncImage:
            source: 'https://res.cloudinary.com/dsmgwupky/image/upload/v1731366361/image_o6cbgf.png'
            size_hint: None, None
            size: '175dp', '175dp'
            pos_hint: {'center_y': 0.66 , 'center_x': 0.5}

        MDCard:
            adaptive_size: True
            pos_hint: {"center_y": 0.40, "center_x": 0.5}
            size_hint: 0.8, 0.1
            theme_bg_color: "Custom"
            md_bg_color: "white"
            md_bg_color_disabled: "white"


            MDRelativeLayout:
                MDTextField:
                    id: name
                    theme_line_color: 'Custom'
                    line_color_normal: 'black'
                    line_color_focus: 'blue'
                    theme_text_color: 'Custom'
                    text_color_focus: 'black'
                    text_color_normal: 'grey'
                    pos_hint: {"center_y": 0.65, "center_x": 0.5}
                    size_hint: 1, None
                    icon_right: "account"
                    mode: "outlined"
                    radius: 15, 15, 15, 15

                    MDTextFieldLeadingIcon:
                        icon: "account-circle-outline"
                        theme_icon_color: 'Custom'
                        icon_color_normal: 'black'
                        icon_color_focus: 'blue'

                    MDTextFieldHintText:
                        theme_text_color: 'Custom'
                        text_color_normal: 'black'
                        text_color_focus: 'grey'
                        text: 'Nome de usuario'

                MDLabel:
                    id: h1
                    text: ''
                    theme_text_color: "Custom"
                    text_color: 'red'
                    pos_hint: {'center_y': 0.1}
                    halign: 'right'
                    font_style: "Label"
                    role: "medium"

        MDCard:
            adaptive_size: True
            pos_hint: {"center_y": 0.29, "center_x": 0.5}
            size_hint: 0.8, 0.1
            theme_bg_color: "Custom"
            md_bg_color: "white"
            md_bg_color_disabled: "white"


            MDRelativeLayout:
                MDTextField:
                    id: password
                    theme_line_color: 'Custom'
                    line_color_normal: 'black'
                    line_color_focus: 'blue'
                    theme_text_color: 'Custom'
                    text_color_focus: 'black'
                    text_color_normal: 'grey'
                    pos_hint: {"center_y": 0.65, "center_x": 0.5}
                    size_hint: 1, None
                    icon_right: "account"
                    mode: "outlined"
                    radius: 15, 15, 15, 15

                    MDTextFieldLeadingIcon:
                        icon: "account-circle-outline"
                        theme_icon_color: 'Custom'
                        icon_color_normal: 'black'
                        icon_color_focus: 'blue'

                    MDTextFieldHintText:
                        theme_text_color: 'Custom'
                        text_color_normal: 'black'
                        text_color_focus: 'grey'
                        text: 'senha'

                MDLabel:
                    id: h2
                    text: ''
                    theme_text_color: "Custom"
                    text_color: 'red'
                    pos_hint: {'center_y': 0.1}
                    halign: 'right'
                    font_style: "Label"
                    role: "medium"

        MDCard:
            style: 'elevated'
            size_hint: 0.8, 0.07
            pos_hint: {"center_y": 0.2, "center_x": 0.5}
            padding: "16dp"
            # Sets custom properties.
            theme_shadow_color: "Custom"
            shadow_color: "black"
            theme_bg_color: "Custom"
            md_bg_color: 0.5, 0.2, 1, 1
            md_bg_color_disabled: "grey"
            theme_shadow_offset: "Custom"
            shadow_offset: (1, -2)
            theme_shadow_softness: "Custom"
            shadow_softness: 1
            theme_elevation_level: "Custom"
            elevation_level: 2
            on_release: root.verificar()

            radius: [15]

            BoxLayout:  # Usa BoxLayout para controlar o layout interno do card
                size_hint: 1, 1
                orientation: 'horizontal'
                padding: 0
                spacing: 0

                MDLabel:
                    text: "Entrar"
                    theme_text_color: "Custom"
                    text_color: "black"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    halign: 'center'
                    font_style: "Title"
                    bold: True
                    role: "medium"



