<Test>:
    name: 'test'
    md_bg_color: 1, 1, 1, 1

    FloatLayout:

        MDLabel:
            text: 'Testando o test'
            halign: 'center'
            bold: True
            font_style: 'Headline'
            role: 'small'
            pos_hint: {'center_x': 0.5, 'center_y': 0.9}

        AsyncImage:
            size_hint: 0.4, 0.4
            pos_hint: {'center_x': 0.5, 'center_y': 0.75}
            source: 'https://res.cloudinary.com/dsmgwupky/image/upload/v1739905708/image_2_wywobo.png'

        MDLabel:
            text: 'Espero encarecidamente que você va se lascar seu fi duma egua'
            padding: [20, 0, 20, 0]
            halign: 'center'
            bold: True
            font_style: 'Title'
            role: 'small'
            theme_text_color: 'Custom'
            text_color: 'grey'
            pos_hint: {'center_x': 0.5, 'center_y': 0.55}
