#: import StoryCreator libs.components.story_creator.StoryCreator

<StepFour>:
    name: 'StepFour'
    md_bg_color: 1, 1, 1, 1

    # Define o canvas no nível do EditarScreen
    canvas.before:
        Rectangle:
            source: "icones/bg1.png"
            size: self.size
            pos: self.pos

    FloatLayout:
        Image:
            source: "icones/gradient.jpg"  # Caminho para a imagem
            allow_stretch: True
            keep_ratio: False  # Faz a imagem se ajustar completamente
            size_hint: 1, 1
            pos_hint: {"center_x": 0.5, "center_y": 0.5}

        MDCard:
            size_hint: 0.9, 0.45
            theme_bg_color: 'Custom'
            md_bg_color: 1, 1, 1, 1
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            MDRelativeLayout:
                MDLabel:
                    text: 'Finalizando o cadastro'
                    font_style: 'Headline'
                    halign: 'center'
                    role: 'small'
                    pos_hint: {'center_y': 0.8, 'center_x': 0.5}

                MDTextField:
                    id: diaria
                    mode: "outlined"
                    size_hint: 0.8, None
                    theme_line_color: 'Custom'
                    line_color_normal: 'grey'
                    pos_hint: {'center_y': 0.55, 'center_x': 0.5}
                    radius: [15,]

                    MDTextFieldHintText:
                        text: 'Valor da diaria'
                    MDTextFieldLeadingIcon:
                        icon: 'cash'

                MDCard:
                    style: 'elevated'
                    size_hint: 0.8, 0.17
                    pos_hint: {'center_y': 0.32, 'center_x': 0.5}
                    theme_shadow_color: "Custom"
                    shadow_color: "brown"
                    theme_bg_color: "Custom"
                    md_bg_color: "black"
                    md_bg_color_disabled: "grey"
                    theme_shadow_offset: "Custom"
                    shadow_offset: (1, -2)
                    theme_shadow_softness: "Custom"
                    shadow_softness: 1
                    theme_elevation_level: "Custom"
                    elevation_level: 2
                    on_release: root.etapa1()

                    MDRelativeLayout:
                        MDLabel:
                            text: 'Finalizar'
                            halign: 'center'
                            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                            theme_text_color: 'Custom'
                            text_color: 'white'
                            bold: True