#: import StoryCreator libs.components.story_creator.StoryCreator

<LoginScreen>:
    name: 'LoginScreen'
    md_bg_color: 1, 1, 1, 1

    FloatLayout:
        MDLabel:
            text: 'Faça login com a senha'
            font_style: 'Headline'
            role: 'medium'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.85}

        MDLabel:
            text: 'Jogador'
            font_style: 'Title'
            role: 'large'
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.55}

        StoryCreator:
            id: story
            halign: 'center'
            size_hint: 0.5, 0.2
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            avatar: 'https://res.cloudinary.com/dsmgwupky/image/upload/v1728587443/4.png'

        MDLabel:
            id: nome
            text: ''
            font_style: 'Title'
            role: 'medium'
            bold: True
            halign: 'center'
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

        MDCard:
            adaptive_size: True
            pos_hint: {"center_y": 0.4, "center_x": 0.5}
            size_hint: 0.8, 0.1
            theme_bg_color: "Custom"
            md_bg_color: "white"
            md_bg_color_disabled: "white"


            MDRelativeLayout:
                MDTextField:
                    id: senha
                    theme_line_color: 'Custom'
                    line_color_normal: 'black'
                    line_color_focus: 'blue'
                    theme_text_color: 'Custom'
                    text_color_focus: 'black'
                    text_color_normal: 'grey'
                    pos_hint: {"center_y": 0.65, "center_x": 0.5}
                    size_hint: 1, None
                    icon_right: "account"
                    mode: "outlined"
                    radius: 15, 15, 15, 15

                    MDTextFieldLeadingIcon:
                        icon: "lock"
                        theme_icon_color: 'Custom'
                        icon_color_normal: 'black'
                        icon_color_focus: 'blue'

                    MDTextFieldHintText:
                        theme_text_color: 'Custom'
                        text_color_normal: 'black'
                        text_color_focus: 'grey'
                        text: 'Senha'

                MDLabel:
                    id: senha_correta
                    text: ''
                    theme_text_color: "Custom"
                    text_color: 'red'
                    pos_hint: {'center_y': 0.1}
                    halign: 'right'
                    font_style: "Label"
                    role: "medium"

        MDCard:
            style: 'elevated'
            size_hint: 0.8, 0.07
            pos_hint: {"center_y": 0.3, "center_x": 0.5}
            padding: "16dp"
            # Sets custom properties.
            theme_shadow_color: "Custom"
            shadow_color: "black"
            theme_bg_color: "Custom"
            md_bg_color: 0.5, 0.2, 1, 1
            md_bg_color_disabled: "grey"
            theme_shadow_offset: "Custom"
            shadow_offset: (1, -2)
            theme_shadow_softness: "Custom"
            shadow_softness: 1
            theme_elevation_level: "Custom"
            elevation_level: 2
            on_release: root.verificar_senha()

            radius: [15]

            BoxLayout:  # Usa BoxLayout para controlar o layout interno do card
                size_hint: 1, 1
                orientation: 'horizontal'
                padding: 0
                spacing: 0

                MDLabel:
                    text: "Entrar"
                    theme_text_color: "Custom"
                    text_color: "black"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    halign: 'center'
                    font_style: "Title"
                    bold: True
                    role: "medium"


