<SendCode>:
    name: 'Send'
    md_bg_color: self.theme_cls.backgroundColor

    FloatLayout:
        AsyncImage:
            source: "https://raw.githubusercontent.com/SatoruGojoMaisForte/logos/main/Images/Logo_chatto/logo3.jpeg"
            size_hint: None, None
            size: "200dp", "150dp"
            pos_hint: {"center_x": 0.5, "center_y": 0.85}
            allow_stretch: True

        MDLabel:
            text: 'Problemas com a senha ao tenta o login'
            bold: True
            font_style: "Title"
            role: "medium"
            halign: "center"
            pos_hint: {"center_y": 0.72, "center_x": 0.5}

        MDLabel:
            text: 'Insira seu email, para que possamos manda um codigo de verificação para recuperar sua conta'
            halign: "center"
            font_style: "Title"
            role: "small"
            size_hint: 0.8, None
            size: 255, 15
            pos_hint: {'center_x': 0.5, 'center_y': 0.66}

        MDTextField:
            id: verificar_email
            hint_text: "Digite o seu E-mail"
            pos_hint: {"center_y": 0.57, "center_x": 0.5}
            size_hint: 0.74, None
            icon_right: "account"
            mode: "outlined"

            MDTextFieldHintText:
                text: "Usuario ou email"

            MDTextFieldTrailingIcon:
                icon: "email"

        MDLabel:
            id: erros
            text: ''
            theme_text_color: "Custom"
            text_color: 'red'
            pos_hint: {"center_y": 0.51, "center_x": 0.65}
            font_style: "Label"
            role: "medium"

        MDButton:
            style: "tonal"
            pos_hint: {"center_y": 0.43, "center_x": 0.5}
            theme_width: "Custom"
            theme_bg_color: "Custom"
            height: "50dp"
            size_hint_x: .74
            md_bg_color: 0, 1, 0.9, 1
            on_release: root.enviar_codigo()

            MDButtonText:
                text: "Enviar verificação"
                theme_text_color: "Custom"
                text_color: "white" if root.theme_cls.theme_style == "Dark" else "black"
                font_style: "Body"
                bold: True
                pos_hint: {"center_y": 0.50, "center_x": 0.5}
                role: "large"

        MDLabel:
            text: 'ou'
            halign: 'center'
            pos_hint: {'center_y': 0.37}
            theme_text_color: "Custom"
            text_color: "white" if root.theme_cls.theme_style == "Dark" else "black"
            font_style: "Title"
            bold: True
            role: "medium"

        MDButton:
            style: "text"
            pos_hint: {'center_y': 0.30, "center_x": 0.5}


            MDButtonText:
                text: "Criar uma conta"
                theme_text_color: "Custom"
                text_color:"white" if root.theme_cls.theme_style == "Dark" else "black"
                font_style: "Title"
                bold: True
                role: "small"

        MDIconButton:
            icon: "arrow-left"
            theme_text_color: "Custom"
            text_color:"white" if root.theme_cls.theme_style == "Dark" else "black"
            pos_hint: {"center_y": 0.95}
            on_release: root.chama_login()